Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 33.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

Conectado correctamente

Cargar Dataset

In [10]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

corredores = pd.read_csv(url)

Exploración de datos

In [11]:
corredores.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [12]:
corredores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

In [13]:
corredores.isnull().sum()

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [15]:
corredores.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [16]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [17]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [18]:
corredores = normalizar_columnas(corredores)
corredores = limpiar_texto(corredores)
corredores = corredores.drop_duplicates()

Funciones especificas

In [19]:
#Normalización de nivel

map_nivel = {
    "mid": "Mid",
    "MID": "Mid",
    "SENIOR": "Senior",
    "senior": "Senior",
    "JUNIOR": "Junior",
    "junior": "Junior",
    "ELITE":"Elite" ,
    "elite" : "Elite"
}

corredores["nivel"] = (
    corredores["nivel"]
    .astype(str)
    .str.strip()
    .replace(map_nivel)
)

#Convertir a entero datos decimal
corredores["anios_experiencia"] = pd.to_numeric(
    corredores["anios_experiencia"],
    errors="coerce"
)


corredores["anios_experiencia"] = corredores["anios_experiencia"].astype("Int64")

In [20]:
corredores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              80 non-null     object
 4   anios_experiencia  76 non-null     Int64
dtypes: Int64(1), int64(1), object(3)
memory usage: 3.3+ KB

In [21]:
corredores.head()

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                  4
1            2    José Ortiz García     Centro    Junior                  0
2            3   María Ramírez Cruz       Centro  Senior                  6
3            4  Fernanda Rojas Cruz          NaN  Senior                  8
4            5      Ana Gómez Rojas          NaN  Senior                  4

Separar validos y rechazados

In [22]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. No debe haber datos vacios

columnas_obligatorias = [
   "id_corredor",
   "nombre",
   "zona",
   "anios_experiencia"
]

condicion_nulos = corredores[columnas_obligatorias].isna().any(axis=1)

condicion_exp_invalida = (
     (corredores["anios_experiencia"] < 0) |
    (corredores["anios_experiencia"] > 50)
)

condicion_rechazo = condicion_nulos | condicion_exp_invalida

rechazados = corredores.loc[condicion_rechazo].copy()
validos = corredores.loc[~condicion_rechazo].copy()

Motivo del rechazo

In [23]:
from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_corredor"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["nombre"]):
    motivos.append("Nombre_nulo")

  if pd.isna(row["zona"]):
    motivos.append("Zona_nula")

  if pd.isna(row["anios_experiencia"]):
    motivos.append("anios_experiencia_nulo")

  elif row["anios_experiencia"] > 50:
      motivos.append("Experiencia_fuera_de_rango")

  return ",".join(motivos)

Agregar motivo de rechazo

In [24]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [25]:
validos.to_csv("corredores_curated.csv", index=False)
rechazados.to_csv("corredores_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [26]:
corredores.head()

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                  4
1            2    José Ortiz García     Centro    Junior                  0
2            3   María Ramírez Cruz       Centro  Senior                  6
3            4  Fernanda Rojas Cruz          NaN  Senior                  8
4            5      Ana Gómez Rojas          NaN  Senior                  4

In [27]:
corredores.dtypes

id_corredor           int64
nombre               object
zona                 object
nivel                object
anios_experiencia     Int64
dtype: object

In [28]:
corredores.isnull().sum()

id_corredor           0
nombre                0
zona                 17
nivel                 0
anios_experiencia     4
dtype: int64

In [29]:
corredores.value_counts()

id_corredor  nombre                       zona         nivel   anios_experiencia
1            José López Flores            Paracentral  Mid     4                    1
2            José Ortiz García              Centro     Junior  0                    1
3            María Ramírez Cruz           Centro       Senior  6                    1
6            Sofía Reyes Hernández        Occidente    Elite   3                    1
7            Pedro Vásquez Torres         Costa        nan     1                    1
8            Paula Ortiz Hernández          Centro     Junior  17                   1
9            Carlos Torres Vásquez        Paracentral  Junior  2                    1
10           Juan Cruz Castillo           Occidente    nan     7                    1
13           Valeria García Torres        Oriente      Senior  23                   1
14           Diego Gómez Chávez             Centro     Senior  20                   1
16           Juan Reyes Morales           Costa        Junior  6                    1
18           Paula Pérez Flores           Oriente      Mid     23                   1
19           Fernanda Ortiz Flores          Centro     Senior  12                   1
21           Juan Hernández Pérez         Oriente      nan     21                   1
22           Andrés Torres García           Centro     Elite   19                   1
23           Paula Mendoza Flores         Centro       Junior  23                   1
25           Andrés Gómez Chávez          Centro       Junior  23                   1
26           Valeria Mendoza Gómez        Occidente    nan     20                   1
27           Carlos Mendoza Torres        Paracentral  Mid     11                   1
28           Carmen Ortiz Mendoza         Centro       Senior  10                   1
30           Carlos Cruz Martínez         Paracentral  Senior  2                    1
31           María Aguilar García         Oriente      Mid     21                   1
32           Ricardo Ortiz Gómez          Costa        Senior  99                   1
33           Karla Rojas Ramírez          Paracentral  Junior  9                    1
35           Diego García Reyes           Centro       Senior  17                   1
36           Diego Santos Cruz            Centro       Junior  22                   1
37           Juan Cruz García             Centro       nan     10                   1
38           María Mendoza Cruz           Costa        Junior  15                   1
40           Ricardo Rojas Ramírez        Occidente    Junior  21                   1
41           Andrés Vásquez Rojas           Centro     Elite   99                   1
42           Juan Hernández Martínez        Centro     Junior  10                   1
43           José Cruz Ramírez            Paracentral  Senior  14                   1
44           Luis Rojas Gómez             Costa        Elite   7                    1
45           María Chávez Ortiz           Occidente    Junior  20                   1
46           Fernanda López García        Paracentral  Mid     13                   1
47           Ricardo Aguilar Ramírez        Centro     Junior  5                    1
48           Lucía López Morales          Costa        nan     25                   1
50           Carlos Ramírez Martínez      Centro       Junior  10                   1
52           Daniela Gómez Martínez       Occidente    nan     5                    1
53           María Torres García          Paracentral  Elite   3                    1
54           Jorge Cruz Santos            Centro       Senior  2                    1
56           Marta Cruz Flores              Centro     Mid     21                   1
57           Carlos Chávez Reyes          Occidente    Junior  14                   1
58           Karla Santos Hernández       Occidente    Senior  6                    1
62           Fernanda Castillo Hernández  Oriente      Senior  3                    1
63           José Ortiz Pérez             Costa        Senior  19                   1
64           Sofía Reyes Ramírez          Costa        Senior  15                   1
65           Valeria Martínez García        Centro     nan     8                    1
66           Juan López Reyes             Oriente      Junior  8                    1
67           Carmen Chávez Ortiz            Centro     Senior  0                    1
68           José García Pérez            Centro       nan     11                   1
69           Jorge Ortiz Pérez              Centro     Mid     1                    1
71           Diego Hernández Vásquez        Centro     Senior  23                   1
72           Luis Cruz Gómez              Oriente      Elite   0                    1
73           Carmen Reyes Rojas           Paracentral  Senior  5                    1
75           Paula Vásquez Castillo       Paracentral  Mid     0                    1
76           Sofía Morales Reyes          Costa        nan     2                    1
78           Fernanda Reyes López         Occidente    Senior  5                    1
79           Jorge Flores Martínez        Occidente    Senior  13                   1
80           Pedro Reyes Rojas            Occidente    Elite   18                   1
Name: count, dtype: int64

In [30]:
validos.to_sql(
    "corredores",
    engine,
    if_exists="append",
    index=False
  )

58

Validar Carga

In [31]:
pd.read_sql(
    "Select * From corredores Limit 100",
    engine
)

,id_corredor,nombre,zona,nivel,anios_experiencia
0,1,José López Flores,Paracentral,Mid,4
1,2,José Ortiz García,Centro,Junior,0
2,3,María Ramírez Cruz,Centro,Senior,6
3,6,Sofía Reyes Hernández,Occidente,Elite,3
4,7,Pedro Vásquez Torres,Costa,nan,1
5,8,Paula Ortiz Hernández,Centro,Junior,17
6,9,Carlos Torres Vásquez,Paracentral,Junior,2
7,10,Juan Cruz Castillo,Occidente,nan,7
8,13,Valeria García Torres,Oriente,Senior,23
9,14,Diego Gómez Chávez,Centro,Senior,20
10,16,Juan Reyes Morales,Costa,Junior,6
11,18,Paula Pérez Flores,Oriente,Mid,23
12,19,Fernanda Ortiz Flores,Centro,Senior,12
13,21,Juan Hernández Pérez,Oriente,nan,21
14,22,Andrés Torres García,Centro,Elite,19
15,23,Paula Mendoza Flores,Centro,Junior,23
16,25,Andrés Gómez Chávez,Centro,Junior,23
17,26,Valeria Mendoza Gómez,Occidente,nan,20
18,27,Carlos Mendoza Torres,Paracentral,Mid,11
19,28,Carmen Ortiz Mendoza,Centro,Senior,10
20,30,Carlos Cruz Martínez,Paracentral,Senior,2
21,31,María Aguilar García,Oriente,Mid,21
22,33,Karla Rojas Ramírez,Paracentral,Junior,9
23,35,Diego García Reyes,Centro,Senior,17
24,36,Diego Santos Cruz,Centro,Junior,22
25,37,Juan Cruz García,Centro,nan,10
26,38,María Mendoza Cruz,Costa,Junior,15
27,40,Ricardo Rojas Ramírez,Occidente,Junior,21
28,42,Juan Hernández Martínez,Centro,Junior,10
29,43,José Cruz Ramírez,Paracentral,Senior,14
30,44,Luis Rojas Gómez,Costa,Elite,7
31,45,María Chávez Ortiz,Occidente,Junior,20
32,46,Fernanda López García,Paracentral,Mid,13
33,47,Ricardo Aguilar Ramírez,Centro,Junior,5
34,48,Lucía López Morales,Costa,nan,25
35,50,Carlos Ramírez Martínez,Centro,Junior,10
36,52,Daniela Gómez Martínez,Occidente,nan,5
37,53,María Torres García,Paracentral,Elite,3
38,54,Jorge Cruz Santos,Centro,Senior,2
39,56,Marta Cruz Flores,Centro,Mid,21
40,57,Carlos Chávez Reyes,Occidente,Junior,14
41,58,Karla Santos Hernández,Occidente,Senior,6
42,62,Fernanda Castillo Hernández,Oriente,Senior,3
43,63,José Ortiz Pérez,Costa,Senior,19
44,64,Sofía Reyes Ramírez,Costa,Senior,15
45,65,Valeria Martínez García,Centro,nan,8
46,66,Juan López Reyes,Oriente,Junior,8
47,67,Carmen Chávez Ortiz,Centro,Senior,0
48,68,José García Pérez,Centro,nan,11
49,69,Jorge Ortiz Pérez,Centro,Mid,1
50,71,Diego Hernández Vásquez,Centro,Senior,23
51,72,Luis Cruz Gómez,Oriente,Elite,0
52,73,Carmen Reyes Rojas,Paracentral,Senior,5
53,75,Paula Vásquez Castillo,Paracentral,Mid,0
54,76,Sofía Morales Reyes,Costa,nan,2
55,78,Fernanda Reyes López,Occidente,Senior,5
56,79,Jorge Flores Martínez,Occidente,Senior,13
57,80,Pedro Reyes Rojas,Occidente,Elite,18