Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 27.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

Conectado correctamente

Cargar Dataset

In [4]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)

Exploración de datos

In [5]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [6]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

In [7]:
polizas.isnull().sum()

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [8]:
polizas.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [9]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [10]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [11]:
polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates()

Funciones especificas

In [12]:
#Convertir fecha a dateTime

polizas["fecha_emision"] = pd.to_datetime(
    polizas["fecha_emision"],
    errors = "coerce",
    format= "mixed"
    )



#Limpiar datos monetarios
polizas["prima"] = (
    polizas["prima"]
    .astype(str)
    .str.replace("","", regex=False)
)



#Convertir a float los datos con decimal
polizas["prima"] = pd.to_numeric(
    polizas["prima"],
    errors = "coerce"
    )

polizas["comision"]= pd.to_numeric(
    polizas["comision"],
    errors = "coerce"
    )

polizas["monto_asegurado"] = pd.to_numeric(
    polizas["monto_asegurado"],
    errors = "coerce"
    )

In [13]:
polizas["fecha_emision"].isnull().sum()

np.int64(2411)

In [14]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            12589 non-null  float64
 7   comision         14926 non-null  float64
 8   monto_asegurado  10185 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

In [15]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,NaN,NaN,139253.11
1,2,2026-02-16,2408,35,11,12,NaN,NaN,NaN
2,3,2025-02-14,540,42,4,9,1611.53,NaN,NaN
3,4,2026-09-01,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,NaN,NaN,123407.75

In [16]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. las fechas deben ser validas
#3. los campos monetarios no pueden quedar vacios o ser nulos

columnas_obligatorias = [
    "id_poliza",
    "fecha_emision",
    "id_cliente",
    "id_corredor",
    "id_aseguradora",
    "id_tipo_seguro",
    "prima",
    "comision",
    "monto_asegurado"
]

validos = polizas[
    polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = polizas [
    polizas[columnas_obligatorias].isna().any(axis=1)
].copy()

rechazados_negativos= polizas[
    (polizas["prima"] < 0) |
    (polizas["comision"] < 0) |
    (polizas["monto_asegurado"] < 0)
].copy()

Motivo del rechazo

In [17]:
def motivo(row):

  motivos = []

  if pd.isna(row["id_poliza"]):
    motivos.append("id_poliza es nulo")

  if pd.isna(row["fecha_emision"]):
    motivos.append("Fecha_emision es nulo")

  if pd.isna(row["id_cliente"]):
    motivos.append("id_cliente es nulo")

  if pd.isna(row["id_corredor"]):
    motivos.append("id_corredor")

  if pd.isna(row["id_aseguradora"]):
    motivos.append("id_aseguradora")

  if pd.isna(row["id_tipo_seguro"]):
    motivos.append("id_tipo_seguro")

  if pd.isna(row["prima"]):
    motivos.append("prima_vacia_o_negativa")

  if pd.isna(row["comision"]):
    motivos.append("comision_vacia_o_negativo")

  if pd.isna(row["monto_asegurado"]):
    motivos.append("monto_asegurado_vacio_o_negativo")

Exportar Archivos

In [18]:
validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

Cargar datos en PostgreSQL

In [19]:
validos.to_sql(
    "polizas",
    engine,
    if_exists="append",
    index=False
  )

751

Validar Carga

In [20]:
pd.read_sql(
    "Select * From polizas Limit 100",
    engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,4,2026-09-01,2821,40,10,5,1866.62,456.99,244461.27
1,7,2025-02-09,1254,25,11,4,1400.82,188.40,258202.93
2,14,2026-01-20,367,65,1,11,0.00,122.12,249504.31
3,19,2025-05-19,1693,50,3,9,1257.43,237.20,106454.95
4,27,2025-06-25,352,30,3,6,-1290.55,179.37,162227.75
...,...,...,...,...,...,...,...,...,...
95,875,2025-04-04,1612,40,11,3,234.59,42.70,8016.21
96,879,2025-02-25,2781,76,9,11,487.84,73.85,41572.74
97,882,2025-07-14,1478,7,3,2,1615.12,339.75,260779.28
98,891,2026-07-01,571,76,11,8,985.40,108.56,155311.42
99,892,2025-10-11,1217,55,13,12,412.35,46.23,44262.23